### ISSUE TITLE
Implement and test internationalization features for the website.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#10]
As a User, I want to be able to navigate to different parts of the web application easily.

Description: Add intuitive site navigation for the User to all content.

**Comment by nathandh** [comment]
Needs some more research. If this involves translation of the site, we could look at **i18n** for maintaining language dictionaries.

However, this needs more research to know what is actually required.

**Comment by nathandh** [comment]
This is a fairly good sized task. Bumping this to Large effort. That would account for the above research, plus actual implementation.
