### ISSUE TITLE
Use Breadcrumbs to track user location and allow for user to be able to easily see where they are on the site.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#11]
User Story(s):

As a User, I want to be able to easily identify the page I am on at any given time and to be able to know where I came from.

Description: Add breadcrumbs to enhance navigation.

**Comment by nathandh** [comment]
Already added in base implementation with Bootstrap: https://getbootstrap.com/docs/5.3/components/breadcrumb/. However, may need some bug fixes. Will look into it.
