### ISSUE TITLE
Validate website by inputting the website URL into the W3C validator tool.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#13]
User Story: As a web developer, I want to ensure that my website adheres to web standards and is accessible to all users, so that I can provide a high-quality user experience and avoid potential issues with usability and search engine optimization.

Description: Use validator to tools to ensure compliance with W3C web standards

**Comment by nathandh** [comment]
Failed initial validation with 1 error. Looking into it and resolving: https://validator.w3.org/nu/?doc=https%3A%2F%2Fnathandh.github.io%2Fmywebclass-simulation%2F

**Comment by nathandh** [comment]
**Various HTML files refactored to resolve Syntax issues**

<img width="1490" alt="Screenshot 2023-03-20 at 11 27 57 PM" src="https://user-images.githubusercontent.com/5404499/226530259-612453e9-69e3-4852-b7a3-db16e335a556.png">

**Comment by nathandh** [comment]
**JS refactored to resolve linting issues**

<img width="919" alt="Screenshot 2023-03-21 at 1 11 21 AM" src="https://user-images.githubusercontent.com/5404499/226530428-0e5be267-1558-4596-a528-5d99df02b2ea.png">
