### ISSUE TITLE
Enable GitHub Pages 

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#15]
User Story: As a website owner, I want to set up a GitHub Pages site to publish my website so that I can easily host my website and make it accessible to anyone with an internet connection.

Description: Enabling GitHub Pages allows you to host a website directly from your GitHub repository.

**Comment by nathandh** [comment]
Need to actually scope effort here

**Comment by jnarlyv** [comment]
Are you referring to the t-shirt sizing or something else?

**Comment by nathandh** [comment]
Correct. Once we decide what the value of our points are, can allocate a size to this task.

**Comment by nathandh** [comment]
Dina had already set our code pushes to mainline to just go to GitHub pages. So this is done. The source repo already had a static.yml file for basic deploy to pages. https://github.com/NJIT-WIS/mywebclass-simulation/blob/master/.github/workflows/static.yml
