### ISSUE TITLE
Create robots.txt file so that site can be indexed properly in Search Engines such as Google.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#16]
User Story(s):

As a product owner, I expect the web application to be easily searched by Google and other Search Engines to improve exposure and finding by educators.

Description: Add a basic setup for crawling by Search Engines.

**Comment by nathandh** [comment]
Need to create this file. Here is a template:

```
User-agent: *
Disallow: /admin/
Disallow: /private/
Disallow: /cgi-bin/
Disallow: /tmp/
Disallow: /temp/
Disallow: /cache/
Disallow: /logs/

User-agent: Googlebot
Disallow: /private/

User-agent: Bingbot
Disallow: /admin/
Disallow: /private/
```

Sitemap: https://www.example.com/sitemap.xml
`

**Comment by jnarlyv** [comment]
create both files sitemap.xml and robots.txt but having trouble adding the files to the root of the repo
