### ISSUE TITLE
Create and submit a sitemap to help search engines crawl and index the website.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#18]
User Story: As product owner, I expect the web application to be easily searched by Google and other Search Engines to improve exposure and finding by educators.

Description: Effective sitemap are associated with improved search engine ranking

**Comment by nathandh** [comment]
Duplicate of Backlog # 16 item to create Robots.txt file for search engine crawling. 
Resolving in favor of: https://github.com/nathandh/mywebclass-simulation/issues/16
