### ISSUE TITLE
Set up a deployment that all members of your team can see to view the progress of the sprint

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#22]
User Story: As product owner, I want code to flow through my pipelines in a manner that ensures quality and reliable output for my users.

**Comment by jnarlyv** [comment]
this issue is the same as enabling GitHub pages?

**Comment by nathandh** [comment]
This was resolved with enabling GitHubPages. Also resolved with enabling Actions, and refining the Docker deployment.
