### ISSUE TITLE
Analyze and review the test results in order to dentify any issues or bugs that were detected.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#25]
User Story: As a web developer, I want to automate the testing of my website's user interface and functionality, so that I can save time and ensure that my website is bug-free and functioning correctly.

Description: Automated test results identified issues and bugs which are fixed to make website more effective

**Comment by nathandh** [comment]
PR #62 will resolve this. Thus far we have 32 tests, and have corrected numerous bugs and made adjustments to improve the user experience throughout the site.
