### ISSUE TITLE
 Create easy-to-understand and reliable instructions for installing the project on the developers mac or Windows computer

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#26]
User Story: As a web developer, I want to automate the testing of my website's user interface and functionality, so that I can save time and ensure that my website is bug-free and functioning correctly.

Description: Automated test results identified issues and bugs which are fixed to make website more effective

**Comment by nathandh** [comment]
Maybe this could include, or be, modification of the README to help with on-boarding to the project.
