### ISSUE TITLE
Review and Combine Project Documentation

### ISSUE THREAD

**Issue by nathandh** [nathandh/mywebclass-simulation#3]
Create a Single team set of Project Documentation

**Comment by nathandh** [comment]
Currently, we have 3 sets of Project Documentation where we did breakdowns of Themes, Initiatives, Epics, Stories, and Tasks on an individual basis. We need to review and combine these into a **single set of Project Documentation** to guide our development effort for MyWebClass.

**Comment by jnarlyv** [comment]
Project documentation was completed and tasks were added to the Sprint 1 backlog.
