### ISSUE TITLE
Implement GDPR requirements with Google Analytics using Consent API and Javascript.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#30]
User Story: As a website owner, I want to make sure that my website is complian with GDPR regulations, so that I can avoid legal fines and protect my customers' privacy.

Description: The GDPR scanner would need to analyze the website for specific issues such as cookie usage, data collection and processing, and privacy policy compliance

**Comment by nathandh** [comment]
We did initial scans with 2gdpr scanner. Results: https://2gdpr.com/939664630
May use a different scanner and see if we get the same passing scores once more before submitting.
