### ISSUE TITLE
Research all areas of Legal Compliance

### ISSUE THREAD

**Issue by nathandh** [nathandh/mywebclass-simulation#4]
Spike research task to understand what is needed for all areas of Legal Compliance for MyWebClass site.

**Comment by nathandh** [comment]
There are various areas we need to understand legal compliance needs. These include: Google Analytics, GDPR requirements, etc. This task is to research and finalize a remaining Sprint 1 plan to tackle all those areas of concern.

**Comment by dina-git** [comment]
https://docs.google.com/presentation/d/1HpbKVjxDZ-UGOB_SLZr5BnGwlmeyLcOnW3M1MMsmTAc/edit#slide=id.p
