### ISSUE TITLE
[Board Card] Initial Project Documentation

### ISSUE THREAD

**Issue by nathandh** [nathandh/mywebclass-simulation#6]
We need to bring over or create initial project documentation in this collaborative MyWebClass Simulation repo. One candidate for documentation aside form commits in the repo would seem to the accompanying Wiki feature. Arly to lead and own this effort. 

From this Board card we should break up and reference smaller tasks at the Sprint Level. A link back to this Board card, at the Sprint Level, would be useful to track overall progress.

**Comment by nathandh** [comment]
Issue 3: Transition of existing project documentation task assigned to Arly in Sprint 1: https://github.com/nathandh/mywebclass-simulation/issues/3

**Comment by jnarlyv** [comment]
updated documentation to include task assignment and story points
