### ISSUE TITLE
 Develop a responsive content template and homepage for the website.

### ISSUE THREAD

**Issue by jnarlyv** [nathandh/mywebclass-simulation#9]
As a User, I want to be able to navigate to different parts of the web application easily.

Description: Add intuitive site navigation for the User to all content.

**Comment by nathandh** [comment]
Maybe this is Sprint 2 task. Will validate.

**Comment by nathandh** [comment]
The site is responsive. It uses Bootstrap to aid in this effort. In addition, we specifically use Bootstrap Navbar which collapses into a 'hamburger icon' with navigation items when the screen size falls below Bootstrap's default small screen threshold.

Finally, validated and fixed so all links work as expected on the site. 

Marking this task as resolved in Sprint 1.
